- docs/source/conf.py
- docs/source/config.rst
- docs/source/index.rst
- docs/source/web_api.rst
- requirements/docs.txt
This is by no means perfect, but it's possibly a step in the right direction.
I choose the best swagger sphinx integration package I could. This one at least feels like we could incrementally make it better. For the time being, I've pointed the dependency at a branch change with fixes in it. Those fixes have been pushed upstream as well.
> Update configuration docs and add web api spec doc

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- tests/conftest.py
- Refactors testing code.
- Corrects the versioning usage similar to what #55 addressed except this is in the testing code..
> Address testing needs

- tests/conftest.py
- tests/unit/conftest.py
Several adjustments to test fixtures and utilities to help with testing needs.
Many of the utility changes aren't in use because they tests that use them aren't written yet. They have been pulled into this PR as a way to provide them for that work as well as other parallel work.
> Adjustments and additions to test fixtures

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- tests/_templates/module.xml
- tests/functional/legacy_publishing/test_module.py
This makes the resources available to the reference resolution code.
Reference resolution was failing before because the resources didn't
exist yet.
Fixes https://github.com/Connexions/nebuchadnezzar/issues/40
> Fix broken links in content

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- tests/_templates/collection.xml
- tests/conftest.py
- tests/functional/legacy_publishing/test_collection.py
> Fix to insert the missing print-style into the metadata record

- docs/source/changes.rst
- press/subscribers/legacy_enqueue.py
> Retry enqueue

- docker-compose.yml
Update cnx-db container from 2.0.1 to 2.1.0
See also #102
> Update cnx-db container from 2.0.1 to 2.1.0

- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
Basically does an upsert of abstract content.
> find and re-use existing abstract in DB, before inserting

- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
> Fix AttributeError for abstractid lookup

- docs/source/changes.rst
- tests/conftest.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_module.py
- tests/helpers.py
Followup to #133 and verifies #132 is fixed.
> Add functional tests for the reuse of the summary/abstract

- .coveragerc
- docker-compose.yml
- docs/source/api.rst
- docs/source/changes.rst
- docs/source/config.rst
- docs/source/index.rst
- docs/source/tasks.rst
- press/celery.py
- press/config.py
- press/tasks.py
- requirements/main.txt
- tests/unit/test_tasks.py
This adds the Celery framework to the project in a pyramid friendly way.
I'm not completely sold on the implementation thus far. It's functional, but the usage is a little funky.
Addresses #114
> Add Celery to the project

- README.rst
Mention that you must have Docker up and running because it isn't obvious for a developer who has never really used Docker before. Installation is easy, so I just added a little side note to instruct devs to install it.
> Update readme, must install docker

- .gitignore
- Makefile
- docker-compose.yml
- press/legacy_publishing/collection.py
- press/utils.py
- press/views/legacy_publishing.py
- requirements/main.txt
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_litezip.py
- tests/functional/views/test_legacy_publishing.py
Should "fix" the pdfs disappearing when using batch.
Addresses #145
> Do only a minor rev when publishing collections

- docker-compose.yml
- docs/source/changes.rst
- press/auth.py
- press/config.py
- press/views/__init__.py
- press/views/auth.py
- press/views/legacy_publishing.py
- press/views/ping.py
- requirements/main.txt
- tests/conftest.py
- tests/functional/views/test_legacy_publishing.py
- tests/functional/views/test_ping.py
Fixes issue https://github.com/Connexions/cnx-press/issues/186
> Add basic authentication for publishing

- Makefile
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- press/models.py
- press/utils.py
- press/views/legacy_publishing.py
- requirements/main.txt
- requirements/test.txt
- tests/conftest.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_module.py
- tests/functional/views/test_legacy_publishing.py
- tests/random_image.py
- tests/unit/test_models.py
- tests/unit/test_utils.py
This enables the publisher to publish resources (e.g. images, video). This does not remove the existing feature of grandfathering over the previous version's resources. This allows the user to associate new resources and overwrite existing resources.
Addresses #144
> WIP Publish Resources

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- tests/conftest.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_module.py
This is needed for the publish images feature.
> litezip provides a Path object, not a filepointer

- docs/source/changes.rst
- press/views/__init__.py
- press/views/ping.py
- tests/functional/views/test_ping.py
Resolves issue https://github.com/Connexions/nebuchadnezzar/issues/84
> Preemptively check credentials

- Jenkinsfile
This adds the deployment and functional testing pipeline to this project.
> Add pipeline for building and deploying Press

- .pyup.yml
https://github.com/openstax/cnx/issues/295
According to the docs (https://pyup.io/docs/bot/config/#schedules), a `.pyup.yml` file in the root dir is 
all we need to config the update frequency.
> Limit pyup to make weekly updates

- docs/source/changes.rst
- requirements/docs.txt
- requirements/main.txt
* Add entry to changelog for new version
* Incorporate update to pyyaml
> Updates for v8.1.1
