openstax/cnx-press

- press/models.py
- press/parsers/__init__.py
- press/parsers/collection.py
- press/parsers/common.py
- press/parsers/module.py
- requirements/main.txt
- tests/unit/parsers/test_collection.py
- tests/unit/parsers/test_module.py
This work enables us to extract metadata information from the litezip models, which are simple wrapping models that represent the structural file elements that make up the content.
> Add models for parsing content metadata from litezip models

- .travis.yml
- Dockerfile
- docker-compose.yml
- press/config.py
- press/legacy_publishing.py
- requirements/main.txt
- requirements/test.txt
- tests/_templates/module.xml
- tests/conftest.py
- tests/functional/conftest.py
- tests/unit/conftest.py
- tests/unit/test_legacy_publishing.py
This only publishes the metadata and content files for a module (aka page).
A future feature will address the publication of resource files.
These changes also contains the addition of cnx-db the library and container. These are used to provide database connectivity and services.
Other elements in these changes include two testing utilities used to aid in the creation and persistence of testing content.
>  Add a function for publishing a legacy module/page

- press/legacy_publishing.py
- requirements/test.txt
- tests/_templates/collection.xml
- tests/conftest.py
- tests/unit/test_legacy_publishing.py
This only publishes the metadata and collection.xml file for a collection (aka book).
A future feature will address the publication of resource files(e.g. cover image, recipe, etc.).
These changes also contain additions to the content and persist testing utilities to handle collection type data.
>  Add a function for publishing a legacy collection/book

- press/legacy_publishing.py
- tests/conftest.py
- tests/unit/test_legacy_publishing.py
This publishes revisions to existing content in a bulk format (litezip).
At this time, the contents of the litezip structure are assumed to have
a collection and optionally have some modules.
These changes also include a way for the content testing utility to generate content relative to each other. That is, relative on the file system. For example, generating a collection with modules will now format the contents on the filesystem to be a litezip filesystem structure.
>  Add a function for publishing litezip formatted content

- press/publishing.py
- press/views/__init__.py
- press/views/api-docs/swagger.yaml
- press/views/publishing.py
- requirements/main.txt
- tests/conftest.py
- tests/functional/views/test_publishing.py
This adds a view to receive a POST containing a litezip structured zipfile for publication.
At this time it is fairly simple. There is no validation other than validating the uploaded file is indeed a zipfile. Later changes will add various content validations to this view.
> Add view to publish an uploaded litezip

- .travis.yml
- Dockerfile
- bin/test
This enables code coverage on this project, which was disabled shortly after it became containerized. This uses one of, if not the recommended easiest, documented ways to connect codecov to test runs using travis-ci and a contained software entity.
> Modify the testing script and config to report code coverage

- press/parsers/common.py
- tests/unit/parsers/test_common.py
This is in accordance with the MDML RNG spec, which says the abstract
is an optional element.
Fixes #17
> Make parsing the abstract optional

- press/publishing.py
- press/views/publishing.py
- tests/conftest.py
- tests/unit/test_publishing.py
This adds an encapsulating directory to the expected litezip file structure. This really isn't necessary, but it's how the completezip zip was fashioned. We'll stick with it because it could provide an option for publishing more than one collection in a litezip payload, though I'm hoping it never comes to that.
This change set also contains an adjustment to the expand_zip function, which in Python 3 can take a path (a string), a file object, or path-like object (pathlib.Path).
Fixes #19
> Include an encapsulating directory when parsing litezip payloads

- press/config.py
- tests/conftest.py
This specifically ignores the warnings coming out of the database table
reflection process. It removes these warnings from the runtime and test output,
which of course makes the output easier to read.
These catch wrappings should probably be moved to cnx-db. I may do that as well...
> Ignore SQLAlchemy SAWarning about unsupported reflection elements

- docker-compose.yml
- docs/source/api.rst
- docs/source/config.rst
- press/config.py
- press/logging.py
- requirements/main.txt
- requirements/test.txt
- tests/unit/test_config.py
- tests/unit/test_logging.py
This adds the framework for logging. None of the existing logic uses it yet, except for application startup code.
This also adds a "debug" concept, which we'll use to turn on debug logging. Later it will be used to enable debugging tools.
> Provide structured application request logging

- bin/test
This adds a simple step to wait for the database to come up before running the tests. This is particularly useful on slower machines or when you've customized your docker-compose config to include the slim dump.
> Check the db services has started before running tests

- .travis.yml
- Dockerfile
- press/views/publishing.py
- tests/_templates/collection.xml
- tests/_templates/module.xml
- tests/functional/views/test_publishing.py
This adds content and identifier validation to the litezip publication view. It stops any invalid content from being added to the database. The response is similar to the response given when a litezip payload is not a valid zip file.
This also fixes the templates, which had validation issues in them due to empty tags that require children.
> Provide content validation during publication of a litezip

- docs/source/api.rst
- docs/source/config.rst
- press/config.py
- press/raven.py
- requirements/main.txt
- tests/unit/test_raven.py
This will enable us to track errors in a Sentry instance.
> Integrate Sentry's Raven client

- Makefile
- bin/test
- docker-compose.test.yml
- docs/source/changes.rst
- tests/conftest.py
This separates the testing configuration into a different docker-compose
file that extends the base file. This specifically mounts the bin directory
and more importantly assigns a 'testing' database separate from the base
database, 'repository'.
This allows one to have a functional database that maintains its data
regardless of test runs. Previously, we would wipe the database before
a test run.
Closes #34
> Add a separate testing configuration

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- tests/unit/legacy_publishing/test_collection.py
- tests/unit/legacy_publishing/test_module.py
On publish assign ``major_version`` rather than ``version`` to prevent
he database triggers that deal with legacy content from manipulating
the record and invoking revision publications.
Addresses #53
> On publish assign major_version rather than version

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/litezip.py
- press/legacy_publishing/module.py
- press/views/legacy_publishing.py
- tests/unit/legacy_publishing/test_collection.py
- tests/unit/legacy_publishing/test_litezip.py
- tests/unit/legacy_publishing/test_module.py
Move the database connection creation into the publishing view code
so that a single transaction can be pushed down through the functions.
This indirectly works towards #53 by enabling a top-level transaction that can encompass both the publication and republications.
> Move the database connection init

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- press/models.py
- tests/conftest.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_module.py
This corrects the issue with missing resource files after publish.
The resource files are now copied from the previous version.
Depends on #76 
Addresses Connexions/nebuchadnezzar#23
> Correct missing resource links on revision publication

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_module.py
This basically removes the line that inserts the revised datetime. We were previously taking this value from the submitted content. Now we are letting the database default to using the current time.
Fixes #81
Fixes Connexions/nebuchadnezzar#35
> Fix publication revised time to use database default column value

- docs/source/api.rst
- docs/source/changes.rst
- press/events.py
- press/views/legacy_publishing.py
Adds before and after events that other code can subscribe to. This may need to be modified, but it's a good first stab.
This will be used as the foundation work for addressing https://github.com/Connexions/nebuchadnezzar/issues/44 and likely many things to come.
> Add before and after events to the legacy publishing request

- docs/source/changes.rst
- press/config.py
- press/events.py
- press/raven.py
- press/subscribers/__init__.py
- press/subscribers/legacy_enqueue.py
- press/views/legacy_publishing.py
- requirements/test.txt
- tests/unit/subscribers/test_init.py
- tests/unit/subscribers/test_legacy_enqueue.py
- tests/unit/test_raven.py
- Add the raven client as a request method. This allows non-critical error
handling to report issues without bubbling it up through the main process.
- Add publication finished event subscriber that contacts the legacy
service to enqueue the content for export file builds (i.e. completezip,
collxml, module export).
Addresses https://github.com/Connexions/nebuchadnezzar/issues/44
(The branch has a different name because this wasn't the original solution, but I forgot to change it)
> Enqueue for export builds when the publication has finished

- docs/source/changes.rst
- press/publishing.py
- press/subscribers/__init__.py
- press/subscribers/track_pubs.py
- tests/unit/subscribers/test_init.py
- tests/unit/subscribers/test_track_pubs.py
- tests/unit/test_publishing.py
Add a publication finished event subscriber that tracks publications to
the filesystem. This is used primarily as a safe guard incase we decide
or need to enable the "republishing" of books with shared pages.
> Add a publication finished event subscriber that tracks publications

- docs/source/changes.rst
- press/subscribers/__init__.py
- press/subscribers/legacy_enqueue.py
- press/subscribers/purge_cache.py
- tests/unit/subscribers/test_init.py
- tests/unit/subscribers/test_purge_cache.py
Add a publication finished event subscriber that purges the cache
for legacy urls that contain the 'latest' version classifier.
Here is example purge url sent by this event subscriber: `https://legacy-qa.cnx.org/content/(col11407|m45231)/latest.*$`
> Add a publication finished event subscriber that purges the cache

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/litezip.py
- press/legacy_publishing/module.py
- press/legacy_publishing/utils.py
- press/utils.py
- press/views/legacy_publishing.py
- tests/functional/legacy_publishing/test_litezip.py
- tests/unit/legacy_publishing/test_utils.py
- tests/unit/test_utils.py
Fix internal usage of the version by consistently using a version tuple (major and minor) between functions rather than the legacy version.
> Fix internal usage of the version as a tuple of major and minor

- docs/source/changes.rst
- press/subscribers/legacy_enqueue.py
- tests/unit/subscribers/test_legacy_enqueue.py
Address legacy enqueuing read timeouts by sorting the content so that
the collection is sent first. All other requests can timeout
without concern. This only addresses the problem and does not fully
resolve it.
Addresses #100
> Address legacy enqueuing read timeouts by sorting the content ids

- docs/source/changes.rst
- press/subscribers/purge_cache.py
This fix produces a message that is just about the ids for the error log line,
rather than printing all the ids to be purged.
> Fix error log entry in the cache purging subscriber

- docs/source/changes.rst
- press/subscribers/__init__.py
- press/subscribers/legacy_enqueue.py
- press/subscribers/legacy_update_latest.py
- press/subscribers/purge_cache.py
- press/utils.py
- tests/helpers.py
- tests/unit/subscribers/test_init.py
- tests/unit/subscribers/test_legacy_enqueue.py
- tests/unit/subscribers/test_legacy_update_latest.py
- tests/unit/subscribers/test_purge_cache.py
- tests/unit/test_utils.py
Collections on legacy do not check the database at every render. The default render path for 'latest' _does_ check, and update the pointer. By fetching that path, we cause the ZODB instance of the collection to be updated. Go ahead and do modules too - it'll pre-populate the varnish cache.
Addresses the (hopefully) last cause of  https://github.com/Connexions/nebuchadnezzar/issues/44
Also, change enqueing to use legacy domain - using the non-legacy is only really needed for PDF generation. This bypasses a problem w/ the non-legacy varnish config, as well.
> Add subscriber to trigger update of legacy latest 

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- press/legacy_publishing/utils.py
- tests/_templates/collection.xml
- tests/_templates/module.xml
- tests/conftest.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_module.py
- tests/unit/legacy_publishing/test_utils.py
The implementation essentially ignores `<md:derived-from ...>...</md:derived-from>`. The database is the source of truth on derivation. Instead of reading this mutable info from the file's contents, the existing record (previous version) is consulted. The parentage information is then carried over to the contextual publication.
The `<md:derived-from url="..."/>` tag is rewritten before insertion into the database. This will ensure the correct info is within the document even though it is ignored by Press.
I choose to use `<md:derived-from url="..."/>` over `<md:derived-from url="...">... other metadata ...</md:derived-from>` because 1) the data is redundant 2) there isn't consistent use of the full form in the content (i.e. modules use this short form) and 3) because it was simplest. …
> Support the publication of derived works to maintain parentage information

- tests/conftest.py
- tests/unit/subscribers/conftest.py
- tests/unit/subscribers/test_legacy_enqueue.py
- tests/unit/subscribers/test_legacy_update_latest.py
- tests/unit/subscribers/test_purge_cache.py
Simple refactor, no logic changed in the application itself
> Refactor subscriber tests to use a common request fixture

- .github/settings.yml
I still think rebase merge is best. I'd keep it enabled, but I'm not sure if people would really know when to validly use it vs squash merge, so let's just do squash.
> Enable squash merge for all pull requests

- docs/source/changes.rst
- press/outofband.py
- press/subscribers/legacy_enqueue.py
- press/subscribers/legacy_update_latest.py
- press/subscribers/purge_cache.py
- tests/helpers.py
- tests/unit/conftest.py
- tests/unit/subscribers/conftest.py
- tests/unit/subscribers/test_legacy_enqueue.py
- tests/unit/subscribers/test_legacy_update_latest.py
- tests/unit/subscribers/test_purge_cache.py
- tests/unit/test_outofband.py
Basically this adjusts all the event subscribers that have HTTP requests to make those HTTP requests as Celery tasks.
We also are taking advantage of using Celery's retry behavior rather than retrying the requests with custom cascading code.
This should correct the latency issues related to waiting for these requests to go through. Addresses #114 
This may not be 100% complete, but it is a step in the right direction. I'm speculating we'll need to add a few lines of configuration for detailing which queue to use, so we don't conflict with the cnx-publishing queues.
> Adjust some event subscriber logic to call async Celery tasks

- requirements/deploy.txt
- requirements/main.txt
- requirements/test.txt
This will allow pyup.io to track changes to any dependencies.
We track those changes here because the app has the authority over it's
dependencies. It also more importantly has the ability exercise the
fitness and feasiblity of upgrading those dependencies through the test suite.
We'll need a way to keep this up-to-date as dependencies get added,
but that will be work for another changeset.
> Pin all versions of dependent packages

- docs/source/changes.rst
- press/errors.py
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- press/views/legacy_publishing.py
- tests/functional/views/test_legacy_publishing.py
Adds a custom error "StaleVersion" which is thrown when the version of the object being published is not equal to the version currently in the database, to avoid "last to publish wins" race conditions.
Includes tests for both a module an a collection-only overwrite.
> Prevent overwrite

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/module.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_module.py
Fix publish submission logic to use the existing 'created' value rather than reading it from the xml document's metadata.
Addresses #148
> Use the existing record's 'created' value

- .jenkins/deploy
This is a copy and paste operation that works of @TomWoodward's deployment Jenkinsfile. I've dropped the deployment part for now. This will at least enable us to release the image on merge to master.
> Add a Jenkinsfile for releasing the Docker image

- docs/source/changes.rst
- docs/source/tasks.rst
- press/views/legacy_publishing.py
- press/views/ping.py
Explicitly disallowing caching. There were some other routes I could not find views for, however.
> Added some cache headers for CNX Press

- press/legacy_publishing/litezip.py
- press/legacy_publishing/utils.py
- tests/conftest.py
- tests/functional/views/test_legacy_publishing.py
- tests/helpers.py
- tests/unit/parsers/test_collection.py
this avoids the ASCII XML ampersand escaping, so the content managers can edit in UTF8
> save unicode/utf8 xml

- requirements/test.txt
`attrs` library isn't being used anywhere in the code anymore.
Found this while merging PRs created by pyup bot (for reference: https://github.com/Connexions/cnx-press/pull/188).
> Remove attrs library from requirements for testing

- press/auth.py
After merging _some_ PRs  by pybot to upgrade some libraries, a warning is raised by every single test. This is because Python's `base64` library renamed `decodestring` to `decodebytes`. This PR gets rid of the warning.
> Rename alias base64 decoder to rm warning

- requirements/test.txt
This is no longer being used. This PR removes the dependency in tests. Found while merging pyup bot PRs (https://github.com/Connexions/cnx-press/pull/175).
> Remove atomicwrites lib from testing dependencies

- setup.cfg
press currently doesn't need this (no line breaks on binary operators) but to stay consistent w/ the other repos, adding it here.
> to be consistent w/ other repos ignore W504

- docs/source/changes.rst
- press/errors.py
- press/legacy_publishing/collection.py
- press/legacy_publishing/litezip.py
- press/legacy_publishing/module.py
- press/legacy_publishing/utils.py
- press/views/api-docs/swagger.yaml
- press/views/legacy_publishing.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_litezip.py
- tests/functional/legacy_publishing/test_module.py
- tests/functional/views/test_legacy_publishing.py
NOTE: This PR contains commits that we intend to revert in the future. They contain the words: temporary fix.
This PR initially was intended to address issue https://github.com/Connexions/cnx-press/issues/265 but then we discovered a corner case that prevented us from making it work and reverted the changes until further notice. Now this PR actually enforces a rule that had only been communicated verbally to the content team: do not make any changes to `collection.xml` files.
> Enforce: changes to collection.xml are not allowed (temporary policy)

- docker-compose.yml
This moves to using the tagged, released, and prebuilt database container.
This should help speed up the testing cycle too, since the image won't
be built on each test run.
See also my comments at https://github.com/Connexions/cnx-db/pull/167#issuecomment-437263856
> Use the latest image of the cnx-db container

- docs/source/changes.rst
- press/exceptions.py
- press/legacy_publishing/collection.py
- press/legacy_publishing/litezip.py
- press/views/legacy_publishing.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_litezip.py
- tests/functional/views/test_legacy_publishing.py
The temporary policy was added because of a corner case that prevented
us from making Press only publish changed content.  Since there will be
a fix for this, we can remove the temporary policy.
----
Part 1/3 of #190
> Undo temporary policy that disallows changes to collection.xml

- docs/source/changes.rst
- press/models/__init__.py
- press/models/press_element.py
- press/parsers/__init__.py
- press/parsers/collection.py
- tests/unit/models/test_press_element.py
- tests/unit/parsers/test_collection.py
- Add PressElement, a collxml element parsed from collection.xml
This is used in the collxml parser in the next commit.
- Add a SAX-based collection.xml parser
This parser will help us determine whether a book needs a major or minor
rev.
----
Part 2/3 of #190
> Add a SAX-based collection.xml parser

- docs/source/changes.rst
- press/legacy_publishing/collection.py
- press/legacy_publishing/litezip.py
- press/legacy_publishing/utils.py
- tests/conftest.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/legacy_publishing/test_litezip.py
- tests/functional/views/test_legacy_publishing.py
- tests/helpers.py
- tests/unit/legacy_publishing/test_utils.py
- Add need_major_rev, need_minor_rev util functions
Add util functions to determine whether the book needs a major or minor
rev using the collxml parser.
- Add ability to detect major / minor rev
With the collxml parser, we can now correctly detect when books should
get a major / minor rev.
---
Part 3/3 of #190
> Add ability to detect major / minor rev

- press/legacy_publishing/utils.py
- tests/functional/legacy_publishing/test_collection.py
- tests/functional/views/test_legacy_publishing.py
(Attempts to) solve https://github.com/openstax/cnx/issues/325
The tests seem to be passing every time now with the given changes. I suspect the problem could've been in this line: `pre.find('content').iter()`. I changed it to `pre.find('content').iter('module')`.
Before, I suspect it was looking at the ordering and text content of the modules' titles when it was supposed to only look at the ordering of the `module`s.
I don't know what else to do about this issue, too. So, if we can go ahead and merge these changes for now. Then we can revisit if necessary.
> Fix intermittent test failures when no rev-ing changes

- requirements/docs.txt
- requirements/lint.txt
- requirements/main.txt
- requirements/test.txt
- tests/conftest.py
In the pytest 4.1.0 changelog:
> Calling fixtures directly is now always an error instead of a warning.
This is the error on travis:
```
______________ ERROR at setup of test_publish_revision_base_case _______________
Fixture "db_tables" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
```
One of the solutions suggested by pytest is to separate the function
that has the fixture decorator and the function that returns the
fixture.  This has been changed in cnx-db so the `db_tables` function
can be …
> Fix "fixture db_tables called directly" in tests
